### PR TITLE
Rewrite of Docker installation process

### PR DESCRIPTION
**Pull request by nmani**
### Sorry for the very large PR.

Rewrote most of the Docker installation workflow to simplify it and create abstractions away from specific Python versions and execution environments. These changes include adding optimized defaults, a multi-stage Docker build, support for modern OCI container standards, podman support, and general workflow optimizations.

These changes will allow for automation in building of image artifacts, unit testing, and creation of pinned releases in the future.

### CODE REVIEW

**Review by JohnOmernik — COMMENTED** [review]
Hot damn, that's a lot of changes.  A few things:

- I had to sneak a small merge into things. Can you merge that into your stuff and resubmit (I don't think the files I change affects any of your files)
- Do we still have different requirements files for different python versions? That was needed because some things got a bit wonky. 
- Can we ensure that the 3.10 requirements match the jupyter_integrations_win_bootstrap repo requirements? I am not sure how to sync this... 
- I wonder if there is a way to take the config template in jupyter_integations_win_bootstrap and take a config like we have created there, and have a docker (or any) install process read that config.  In fact, I wonder if this docker folder should be moved out into a docker_boostrap? or if bootstraps are their own repo, and the configs are platform independent but the bootstraps load the config and do the stuff.   Thoughts? This docker install was designed for generic hard coded installs while the bootstrap is much more configurable, even to the point of using internal repos if you so want to setup.

**Comment by nmani** [comment]
Yah, I can do that. I'll rebase it with latest and resolve any merge conflicts that come up. There shouldn't be any IMO.

**Comment by nmani** [comment]
We can do different requirements.txt for different Python versions within 3.9+ but most of the packages should be left floating to latest or on major version release (ie- "pandas==2.* "). Unless there's a backward compatibility, regression bug, or version pinning argument, there isn't an need to pin it IMO. When such an issue is discovered, you can add into requirements.txt as the minimum supported version across ALL Python 3.9+ versions. Based on my quick review of the code, I didn't see any Python 3.10+ specific syntax used so we should be good there.

Also a lot of core libraries also have constant security and bug updates so you don't want have to read a dozens of changelogs to discover this. Luckily Github will search for and alert you to these issues sometimes.

**Review by JohnOmernik — APPROVED** [review]
Looks good, I think we should discuss with @robd518 and look at moving the Docker stuff out of integrations base and moving it into a bootstrap folder where we can have a unified config regardless of platform.

**Pull request merged**
